version: "3.3"
services:
  tools:
    image: robertdcurrier/phytotracker5
    container_name: pt5
    user: "${UID}:${GID}"
    command: tail -f /dev/null
    volumes:
      - .:/pt5
      - /Volumes/data/:/data/
    working_dir: /pt5
